version: '3.8'
services:
  lightricks-finetune:
    image: aeorlov/ados-workspace-cuda13.0:v.0.0.21
    environment:
      - GCS_BUCKET=ltx-ados-2026
      - GCS_MOUNT_PATH=/mnt/gcs
    ports:
      - "8889:8888"
      - "2222:22"
      - "7681:7681"
      - "8188:8188"
    volumes:
      - checkpoints:/mnt/data
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

volumes:
  checkpoints:
